<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FirstTask.aspx.cs" Inherits="Asp.Net.FirstTask" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            font-size: xx-large;
        }
        .auto-style2 {
            font-size: x-large;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <span class="auto-style1"><strong>Документ &quot;Продажа&quot;</strong></span><br />
            <br />
            <span class="auto-style2">Шапка документа</span><br />

        </div>
        <asp:GridView ID="HeaderGridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Номер_Продажи" DataSourceID="HeaderDataSource" ForeColor="Black" GridLines="Vertical" SelectedIndex="0">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="Номер_Продажи" HeaderText="Номер_Продажи" InsertVisible="False" ReadOnly="True" SortExpression="Номер_Продажи" />
                <asp:BoundField DataField="Дата" HeaderText="Дата" SortExpression="Дата" />
                <asp:BoundField DataField="Номер_Карты" HeaderText="Номер_Карты" SortExpression="Номер_Карты" />
                <asp:BoundField DataField="Сумма_Продажи" HeaderText="Сумма_Продажи" SortExpression="Сумма_Продажи" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <asp:SqlDataSource ID="HeaderDataSource" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:BookWorldDataBaseConnectionString %>" DeleteCommand="DELETE FROM [Продажа] WHERE [Номер_Продажи] = @original_Номер_Продажи AND [Дата] = @original_Дата AND (([Номер_Карты] = @original_Номер_Карты) OR ([Номер_Карты] IS NULL AND @original_Номер_Карты IS NULL)) AND (([Сумма_Продажи] = @original_Сумма_Продажи) OR ([Сумма_Продажи] IS NULL AND @original_Сумма_Продажи IS NULL))" InsertCommand="INSERT INTO [Продажа] ([Дата], [Номер_Карты], [Сумма_Продажи]) VALUES (@Дата, @Номер_Карты, @Сумма_Продажи)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Продажа]" UpdateCommand="UPDATE [Продажа] SET [Дата] = @Дата, [Номер_Карты] = @Номер_Карты, [Сумма_Продажи] = @Сумма_Продажи WHERE [Номер_Продажи] = @original_Номер_Продажи AND [Дата] = @original_Дата AND (([Номер_Карты] = @original_Номер_Карты) OR ([Номер_Карты] IS NULL AND @original_Номер_Карты IS NULL)) AND (([Сумма_Продажи] = @original_Сумма_Продажи) OR ([Сумма_Продажи] IS NULL AND @original_Сумма_Продажи IS NULL))">
            <DeleteParameters>
                <asp:Parameter Name="original_Номер_Продажи" Type="Int32" />
                <asp:Parameter DbType="Date" Name="original_Дата" />
                <asp:Parameter Name="original_Номер_Карты" Type="Int32" />
                <asp:Parameter Name="original_Сумма_Продажи" Type="Decimal" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter DbType="Date" Name="Дата" />
                <asp:Parameter Name="Номер_Карты" Type="Int32" />
                <asp:Parameter Name="Сумма_Продажи" Type="Decimal" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter DbType="Date" Name="Дата" />
                <asp:Parameter Name="Номер_Карты" Type="Int32" />
                <asp:Parameter Name="Сумма_Продажи" Type="Decimal" />
                <asp:Parameter Name="original_Номер_Продажи" Type="Int32" />
                <asp:Parameter DbType="Date" Name="original_Дата" />
                <asp:Parameter Name="original_Номер_Карты" Type="Int32" />
                <asp:Parameter Name="original_Сумма_Продажи" Type="Decimal" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="BodyDataSource" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:BookWorldDataBaseConnectionString %>" DeleteCommand="DELETE FROM [Состав_Продажи] WHERE [Номер_Продажи] = @original_Номер_Продажи AND [Код_Товара] = @original_Код_Товара AND [Количество] = @original_Количество" InsertCommand="INSERT INTO [Состав_Продажи] ([Номер_Продажи], [Код_Товара], [Количество]) VALUES (@Номер_Продажи, @Код_Товара, @Количество)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Состав_Продажи] WHERE ([Номер_Продажи] = @Номер_Продажи)" UpdateCommand="UPDATE [Состав_Продажи] SET [Количество] = @Количество WHERE [Номер_Продажи] = @original_Номер_Продажи AND [Код_Товара] = @original_Код_Товара AND [Количество] = @original_Количество">
            <DeleteParameters>
                <asp:Parameter Name="original_Номер_Продажи" Type="Int32" />
                <asp:Parameter Name="original_Код_Товара" Type="Int32" />
                <asp:Parameter Name="original_Количество" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Номер_Продажи" Type="Int32" />
                <asp:Parameter Name="Код_Товара" Type="Int32" />
                <asp:Parameter Name="Количество" Type="Int32" />
            </InsertParameters>
            <SelectParameters>
                <asp:ControlParameter ControlID="HeaderGridView" Name="Номер_Продажи" PropertyName="SelectedValue" Type="Int32" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="Количество" Type="Int32" />
                <asp:Parameter Name="original_Номер_Продажи" Type="Int32" />
                <asp:Parameter Name="original_Код_Товара" Type="Int32" />
                <asp:Parameter Name="original_Количество" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
        <br />
        <asp:Button ID="AddToHeadButton" runat="server" OnClick="AddToHeadButton_Click" Text="Добавить запись в шапку" />
        <br />
        <br class="auto-style2" />
        <span class="auto-style2">Табличная часть</span><br />
        <br />
        <asp:GridView ID="BodyGridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Номер_Продажи,Код_Товара" DataSourceID="BodyDataSource" ForeColor="Black" GridLines="Vertical">
            <AlternatingRowStyle BackColor="#CCCCCC" />
            <Columns>
                <asp:BoundField DataField="Номер_Продажи" HeaderText="Номер_Продажи" ReadOnly="True" SortExpression="Номер_Продажи" />
                <asp:BoundField DataField="Код_Товара" HeaderText="Код_Товара" ReadOnly="True" SortExpression="Код_Товара" />
                <asp:BoundField DataField="Количество" HeaderText="Количество" SortExpression="Количество" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#808080" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        <br />
        Код товара&nbsp;&nbsp;&nbsp; <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <br />
        <br />
        Количество&nbsp;&nbsp; <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
        <br />
        <br />
        <br />
        <asp:Button ID="AddRecordToTableButton" runat="server" OnClick="AddRecordToTableButton_Click" Text="Добавить запись в табличную часть" />
        <br />
        <br />
        <br />
        <asp:Button ID="TakeALookButton" runat="server" OnClick="TakeALookButton_Click" Text="Посмотреть выбранный документ" />
        <br />
        <br />
        <br />
        <asp:LinkButton ID="LinkButton1" runat="server" OnClick="LinkButton1_Click">Вернуться на главную</asp:LinkButton>
    </form>
</body>
</html>
